# Generated by Django 3.2.7 on 2021-10-11 21:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211011_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='artist_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='artist'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
    ]
