# Generated by Django 3.2.7 on 2021-10-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211011_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='artist_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='title_slug',
            field=models.SlugField(null=True),
        ),
    ]
