# Generated by Django 3.2.7 on 2021-10-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211011_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='title_slug',
        ),
    ]
