# Generated by Django 3.2.7 on 2021-11-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_submitlyrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitLyrics',
        ),
    ]
