# Generated by Django 3.2.7 on 2021-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_submitlyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lyrics_admin',
            field=models.BooleanField(default=False),
        ),
    ]
